### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by AREEG94FAHAD** [gistnetserv-uah/RPL#2]
Hi @h-hosseini  I did exactly what you said  but this message appears to me after running.

![img1](https://user-images.githubusercontent.com/30151596/116517587-daf73080-a8d7-11eb-87a7-1d5efce9ed73.PNG)

and this 

![img2](https://user-images.githubusercontent.com/30151596/116517640-ea767980-a8d7-11eb-8eef-2c2c45d9adbd.PNG)

Also when I run it using Cmdenv this error appear

![img3](https://user-images.githubusercontent.com/30151596/116519012-a5ebdd80-a8d9-11eb-9fc3-3947c001385b.PNG)

**Comment by h-hosseini** [comment]
Hi @AREEG94FAHAD,
Regarding the first error, we terminated the simulation by calling the function of `endSimulation()` after converging the protocol. The attached figure and links show the class including the code and the function call. 
[endSimulation() at line 107](https://github.com/NETSERV-UAH/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_UnlimitedRadio_V3/src/statisticcollector/StatisticCollector.cc/#L107)
[endSimulation() at line 155](https://github.com/NETSERV-UAH/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_UnlimitedRadio_V3/src/statisticcollector/StatisticCollector.cc/#L155)

![1](https://user-images.githubusercontent.com/34283881/116543498-2ffc6c00-a903-11eb-99da-580be1a8e495.jpg)

**Comment by h-hosseini** [comment]
In general, the collected parameters has been described in [this article: "Outperforming RPL with scalable routing based on meaningful MAC addressing"](https://www.sciencedirect.com/science/article/abs/pii/S1570870521000147). The mentioned class works based on that parameters. you can customize the class according to your work and parameters.

**Comment by h-hosseini** [comment]
Regarding the finger print, I didn't set the finger print based on the finger print algorithm described in the OMNeT++ documentation. You can do it or remove it from the *.ini file.

**Comment by h-hosseini** [comment]
About Cmdenv, I attached figures. I think the blue box may be the problem. mop1.ini includes two scenarios (Configs), select one of them before running the simulation.

![2](https://user-images.githubusercontent.com/34283881/116546194-920aa080-a906-11eb-879f-a3a757de61e6.jpg)

and

![3](https://user-images.githubusercontent.com/34283881/116546234-9e8ef900-a906-11eb-8378-1b91cd5e7c8c.jpg)

**Comment by AREEG94FAHAD** [comment]
Thank you so much it work fine now.
I just have a question, is that execution time in the figure below?
And when I open the folder of "averageSentDAO" it means each second send for example 1.5 message right?
And what is the size of packet?

![RPLssssss](https://user-images.githubusercontent.com/30151596/116809917-5d3a5b80-ab49-11eb-8df2-9d541624b25d.PNG)

**Comment by h-hosseini** [comment]
We wanted to run the simulation 10 times. By setting "repeat = 10", OMNeT++ run it 10 times.
Since nodes are randomly distributed/located in the network, we have defined the limitation of "sim-time-limit = 1000s" in the simulation to terminate the simulation when there is a node which is not in the transmission range of other nodes because the network is not converged in this case.
Regarding "averageSentDAO", no, it is not average per **second or time**. It is average per **node**. If we assume that G is a network with N nodes, G = {node 1, node 2, ..., node N}, then averageSentDAO = (SUM Number of DAOs sent by node i) / (N) for each i 𝞊 G.
Since we developed and used an ideal radio, the parameter of the size of packet does not affect on the results. If you want to use IEEE 802.15.4 as the radio, you should check and set that parameter.

**Comment by AREEG94FAHAD** [comment]
Dear Hedayat Hosseini I hope you are doing well.
I just have a question. It is  work fine with 200 nodes or less. but when I increase the number of node to 250 as shown in figure below.  the program it work but the result files not appears in result folder. Do you have any advice.
Is that correct way to increase the number of nodes?

![fig1](https://user-images.githubusercontent.com/30151596/120790905-343c2a80-c53c-11eb-992f-dca28bae957d.PNG)


Thank you again for your help and your effort.

**Comment by h-hosseini** [comment]
Dear @AREEG94FAHAD ,
Thank you! I hope you are well, too!
I tested the storing simulation with 250 nodes according to your settings, and it generated the result files. If the problem has not been resolved, I should see what is happening. Can you send more screenshots (Run Configuration, ... )?

**Comment by AREEG94FAHAD** [comment]
Dear @h-hosseini 
I just have  some questions.

1- Where can I find code that relative to K, Imin and DIS trickle algorithm?

2- In result files. I found four type of convergence time as below.
- 01_1_convergenceTimeUpward.txt
- 01_2_convergenceTimeDownward.txt
- convergenceTimeEndDownward.txt
- convergenceTimeEndUpward.txt
My question is what are the different between them. What is the unit of each time in these files?

3- Where can I find the collision result of DIO and DIS?

May I get copy of your paper [Outperforming RPL with scalable routing based on meaningful MAC addressing](https://www.sciencedirect.com/science/article/abs/pii/S1570870521000147) 

Thank you again for your time. I really appreciate your efforts to read and answering my questions.

**Comment by h-hosseini** [comment]
Dear @AREEG94FAHAD ,

sorry for the delay!
Parameters of the trickle algorithm are available [here at lines 69 ~ 71](https://github.com/NETSERV-UAH/RPL/blob/master/OMNeTpp5_2_1_INET3_6_3/RPL_UnlimitedRadio_V3/src/networklayer/icmpv6/RPLUpwardRouting.ned#L69)

**Comment by h-hosseini** [comment]
Regarding a copy of [Outperforming RPL with scalable routing based on meaningful MAC addressing](https://www.sciencedirect.com/science/article/abs/pii/S1570870521000147), I think Dr. @ElisaRojas can help you better than me because I have little knowledge about the copyright laws in this case. Anyway, you can request her in [Research Gate](https://www.researchgate.net/publication/348679208_Outperforming_RPL_with_scalable_routing_based_on_meaningful_MAC_addressing), too.

About the convergence time, we mentioned "**it is the interval time from the startup of RPL until the latest node joins the DODAG**". Since RPL uses some MoPs, there are different calculations to calculate this parameter.

When you use MoP0, you only use Upward routes. Therefore, the convergenceTimeEnd is time when the last node is joined to the Upward graph. Now, convergenceTimeUpward  = convergenceTimeEndUpward - startup of RPL.

When you use MoP1 or 2, convergenceTimeEnd is time when the last node is joined to the Downward graph since you use both Upward and Downward routes in these MoPs. I mean you first create Upward routes and then create Downward routes based on the generated Upward routs. Therefore, convergenceTimeDownward  = convergenceTimeEndDownward - startup of RPL.

**Comment by h-hosseini** [comment]
About the collision result of DIO and DIS, since we used our ideal radio, no collision occurs. To evaluate this parameter, I think you should use IEEE 802.15.4 radio and use/customize its capabilities.

**Comment by ElisaRojas** [comment]
Hi @AREEG94FAHAD ,

For the article, please request it via RG at: https://www.researchgate.net/publication/348679208_Outperforming_RPL_with_scalable_routing_based_on_meaningful_MAC_addressing
And we'll send a pre-print copy. It's not the final version, but it's the one we can officially share according to the 2-year embargo rule of its editorial :)

Thank you!

**Comment by AREEG94FAHAD** [comment]
Thank you so much @h-hosseini @ElisaRojas 
I hope this will be the last question. What is the unit of the value in the figure below. Is it second?
![lastq](https://user-images.githubusercontent.com/30151596/122211646-a2271100-ceaf-11eb-9dd3-23766eaf6b18.PNG)

**Comment by h-hosseini** [comment]
Yes, It is the second.

**Comment by h-hosseini** [comment]
Help wanted
